services:
  postgres:
    container_name: postgres-bsn
    image: postgres:17  # Spécifiez une version
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bsndb
      # PGDATA retiré - utilise le défaut
    volumes:
      - postgres:/var/lib/postgresql/data  # Corrigé
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d bsndb" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  mail-dev:
#    container_name: mail-dev-bsn
#    image: maildev/maildev
#    ports:
#      - "1080:1080"
#      - "1025:1025"

  # Config for building api container
  bsn-api:
    container_name: bsn-api
    image: jramde/bsn-api:1.0.0
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres # bsn-api start on running after postgres started running

  # Config to run the frontend app
  bsn-ui:
    container_name: bsn-ui
    image: jramde/bsn-ui:1.0.0
    ports:
      - 8080:80 # 8080 is the port we'll use; 80 is the nginx default port
    networks:
      - spring-demo
    depends_on:
      - bsn-api

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local