spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bsndb
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Mailing
  mail:
    host: ${EMAIL_HOSTNAME}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true
    protocol: smtp
#  mail:
#    host: smtp.gmail.com
#    port: 465
#    username: restonspositifs2@gmail.com
#    password: ygyp vpty seya lhmg
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
#            trust: "*"
#        starttls:
#          enable: true
#    protocol: smtp

application:
  security:
    jwt:
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

  # CORS : Localhost: Angular, Nginx; VPS: Backend, Frontend
  cors:
    origins: http://localhost:4200,http://localhost:8080,http://my_ip_address:8088,http://my_ip_address:8080
  file:
    upload:
      photos-output-path: ./uploads

# Swagger local url
# http://localhost:8088/api/v1/swagger-ui/index.html
server:
  port: 8088
