spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bsndb
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Mailing
  # By using env variables, spring will try to read any environment variables
  # from the system or project calling like that
  # localhost and dummy are default values before we up on prod
  mail:
    host: ${EMAIL_HOSTNAME:localhost}
    username: ${EMAIL_USERNAME:dummy}
    password: ${EMAIL_PASSWORD:dummy}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true
    protocol: smtp

# Application config
application:
  security:
    jwt:
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

  # CORS : Localhost for Angular and Backend driven by Nginx;
  # VPS: Use VPS_IP_ADDRESS for Angular loaded by Nginx and the Backend
  cors:
    origins: http://localhost:4200,http://localhost:8080,http://51.210.5.36:8080,http://51.210.5.36:8088
  file:
    upload:
      photos-output-path: ./uploads

# Swagger local url
# http://localhost:8088/api/v1/swagger-ui/index.html
server:
  port: 8088
