name: BSN Frontend Pipeline

on:
  push:
    branches:
      - ci/pipeline
    paths:
      - bsn-frontend/**
      - docker/frontend/**
      - 'docker-compose.yml'
      - .github/workflows/*-frontend.yml

jobs:
  build-image:
    name: Build Frontend Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Extract project version and store it in the variable VERSION
      - name: Extract project version
        id: extract_version
        run: |
          cd bsn-frontend
          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      # Login to DockerHub with my credentials
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build & Push to DockerHub
      - name: Build & Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./bsn-frontend
          file: ./docker/frontend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bsn-ui:${{ steps.extract_version.outputs.VERSION }},${{ secrets.DOCKER_HUB_USERNAME }}/bsn-ui:latest

  # Deploy the application
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: [build-image]
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_ed25519_ovh_bsn_vps
          chmod 600 ~/.ssh/id_ed25519_ovh_bsn_vps
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Create Deployment folder
        run: ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p ci-cd"

      - name: Copy docker-compose file
        run: scp docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:ci-cd/docker-compose.yml

      - name: Set environment variables and deploy
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
          cd ci-cd
          docker-compose -f docker-compose.yml pull -q
          docker-compose -f docker-compose.yml up -d
          EOF